// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pb/assets.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Languages int32

const (
	Languages_UnknownLanguage    Languages = 0
	Languages_SimplifiedChinese  Languages = 1 // 简体中文
	Languages_TraditionalChinese Languages = 2 // 繁体中文
	Languages_Japanese           Languages = 3 // 日语
)

// Enum value maps for Languages.
var (
	Languages_name = map[int32]string{
		0: "UnknownLanguage",
		1: "SimplifiedChinese",
		2: "TraditionalChinese",
		3: "Japanese",
	}
	Languages_value = map[string]int32{
		"UnknownLanguage":    0,
		"SimplifiedChinese":  1,
		"TraditionalChinese": 2,
		"Japanese":           3,
	}
)

func (x Languages) Enum() *Languages {
	p := new(Languages)
	*p = x
	return p
}

func (x Languages) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Languages) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_assets_proto_enumTypes[0].Descriptor()
}

func (Languages) Type() protoreflect.EnumType {
	return &file_pb_assets_proto_enumTypes[0]
}

func (x Languages) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Languages.Descriptor instead.
func (Languages) EnumDescriptor() ([]byte, []int) {
	return file_pb_assets_proto_rawDescGZIP(), []int{0}
}

type PriceUnit int32

const (
	PriceUnit_UnknownPriceUnit PriceUnit = 0
	PriceUnit_CNY              PriceUnit = 1 // 人民币
	PriceUnit_JPY              PriceUnit = 2 // 日元
	PriceUnit_USD              PriceUnit = 3 // 美元
)

// Enum value maps for PriceUnit.
var (
	PriceUnit_name = map[int32]string{
		0: "UnknownPriceUnit",
		1: "CNY",
		2: "JPY",
		3: "USD",
	}
	PriceUnit_value = map[string]int32{
		"UnknownPriceUnit": 0,
		"CNY":              1,
		"JPY":              2,
		"USD":              3,
	}
)

func (x PriceUnit) Enum() *PriceUnit {
	p := new(PriceUnit)
	*p = x
	return p
}

func (x PriceUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriceUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_assets_proto_enumTypes[1].Descriptor()
}

func (PriceUnit) Type() protoreflect.EnumType {
	return &file_pb_assets_proto_enumTypes[1]
}

func (x PriceUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriceUnit.Descriptor instead.
func (PriceUnit) EnumDescriptor() ([]byte, []int) {
	return file_pb_assets_proto_rawDescGZIP(), []int{1}
}

type AssetsMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`     // 唯一主键
	Code  uint64                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"` // 资产码，一物并不一定会有一码
	Name  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`  // 资产名
	// Types that are valid to be assigned to Detail:
	//
	//	*AssetsMeta_Book
	//	*AssetsMeta_Cd
	Detail        isAssetsMeta_Detail `protobuf_oneof:"detail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetsMeta) Reset() {
	*x = AssetsMeta{}
	mi := &file_pb_assets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetsMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetsMeta) ProtoMessage() {}

func (x *AssetsMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_assets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetsMeta.ProtoReflect.Descriptor instead.
func (*AssetsMeta) Descriptor() ([]byte, []int) {
	return file_pb_assets_proto_rawDescGZIP(), []int{0}
}

func (x *AssetsMeta) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssetsMeta) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AssetsMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssetsMeta) GetDetail() isAssetsMeta_Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *AssetsMeta) GetBook() *BookAssets {
	if x != nil {
		if x, ok := x.Detail.(*AssetsMeta_Book); ok {
			return x.Book
		}
	}
	return nil
}

func (x *AssetsMeta) GetCd() *CDAssets {
	if x != nil {
		if x, ok := x.Detail.(*AssetsMeta_Cd); ok {
			return x.Cd
		}
	}
	return nil
}

type isAssetsMeta_Detail interface {
	isAssetsMeta_Detail()
}

type AssetsMeta_Book struct {
	Book *BookAssets `protobuf:"bytes,4,opt,name=book,proto3,oneof"` // 图书类型资产
}

type AssetsMeta_Cd struct {
	Cd *CDAssets `protobuf:"bytes,5,opt,name=cd,proto3,oneof"` // 专辑类型资产
}

func (*AssetsMeta_Book) isAssetsMeta_Detail() {}

func (*AssetsMeta_Cd) isAssetsMeta_Detail() {}

type PriceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          PriceUnit              `protobuf:"varint,1,opt,name=unit,proto3,enum=pb.PriceUnit" json:"unit,omitempty"`                      // 货币单位
	Price         uint32                 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`                                      // 标价
	PurchasePrice uint32                 `protobuf:"varint,3,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"` // 售价
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceInfo) Reset() {
	*x = PriceInfo{}
	mi := &file_pb_assets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceInfo) ProtoMessage() {}

func (x *PriceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_assets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceInfo.ProtoReflect.Descriptor instead.
func (*PriceInfo) Descriptor() ([]byte, []int) {
	return file_pb_assets_proto_rawDescGZIP(), []int{1}
}

func (x *PriceInfo) GetUnit() PriceUnit {
	if x != nil {
		return x.Unit
	}
	return PriceUnit_UnknownPriceUnit
}

func (x *PriceInfo) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceInfo) GetPurchasePrice() uint32 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

type BookAssets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        []string               `protobuf:"bytes,1,rep,name=author,proto3" json:"author,omitempty"`                                  // 作者
	Publisher     string                 `protobuf:"bytes,2,opt,name=publisher,proto3" json:"publisher,omitempty"`                            // 出版/出品/销售方
	Tag           []string               `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag,omitempty"`                                        // 标签
	Language      Languages              `protobuf:"varint,4,opt,name=language,proto3,enum=pb.Languages" json:"language,omitempty"`           // 语言
	PurchaseTime  uint64                 `protobuf:"varint,5,opt,name=purchase_time,json=purchaseTime,proto3" json:"purchase_time,omitempty"` // 购入时间
	Price         *PriceInfo             `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`                                    // 价格信息
	Signed        bool                   `protobuf:"varint,7,opt,name=signed,proto3" json:"signed,omitempty"`                                 // 有无签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookAssets) Reset() {
	*x = BookAssets{}
	mi := &file_pb_assets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookAssets) ProtoMessage() {}

func (x *BookAssets) ProtoReflect() protoreflect.Message {
	mi := &file_pb_assets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookAssets.ProtoReflect.Descriptor instead.
func (*BookAssets) Descriptor() ([]byte, []int) {
	return file_pb_assets_proto_rawDescGZIP(), []int{2}
}

func (x *BookAssets) GetAuthor() []string {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *BookAssets) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *BookAssets) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *BookAssets) GetLanguage() Languages {
	if x != nil {
		return x.Language
	}
	return Languages_UnknownLanguage
}

func (x *BookAssets) GetPurchaseTime() uint64 {
	if x != nil {
		return x.PurchaseTime
	}
	return 0
}

func (x *BookAssets) GetPrice() *PriceInfo {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *BookAssets) GetSigned() bool {
	if x != nil {
		return x.Signed
	}
	return false
}

type CDAssets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        []string               `protobuf:"bytes,1,rep,name=author,proto3" json:"author,omitempty"`                                  // 作者
	Publisher     string                 `protobuf:"bytes,2,opt,name=publisher,proto3" json:"publisher,omitempty"`                            // 出版/出品/销售方
	Year          uint32                 `protobuf:"varint,3,opt,name=Year,proto3" json:"Year,omitempty"`                                     // 年份
	Language      Languages              `protobuf:"varint,4,opt,name=language,proto3,enum=pb.Languages" json:"language,omitempty"`           // 语言
	Track         uint32                 `protobuf:"varint,5,opt,name=track,proto3" json:"track,omitempty"`                                   // 曲目数
	Tag           []string               `protobuf:"bytes,6,rep,name=tag,proto3" json:"tag,omitempty"`                                        // 标签
	PurchaseTime  uint64                 `protobuf:"varint,7,opt,name=purchase_time,json=purchaseTime,proto3" json:"purchase_time,omitempty"` // 购入时间
	Price         *PriceInfo             `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`                                    // 价格信息
	Signed        bool                   `protobuf:"varint,9,opt,name=signed,proto3" json:"signed,omitempty"`                                 // 有无签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CDAssets) Reset() {
	*x = CDAssets{}
	mi := &file_pb_assets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CDAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDAssets) ProtoMessage() {}

func (x *CDAssets) ProtoReflect() protoreflect.Message {
	mi := &file_pb_assets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDAssets.ProtoReflect.Descriptor instead.
func (*CDAssets) Descriptor() ([]byte, []int) {
	return file_pb_assets_proto_rawDescGZIP(), []int{3}
}

func (x *CDAssets) GetAuthor() []string {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *CDAssets) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *CDAssets) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CDAssets) GetLanguage() Languages {
	if x != nil {
		return x.Language
	}
	return Languages_UnknownLanguage
}

func (x *CDAssets) GetTrack() uint32 {
	if x != nil {
		return x.Track
	}
	return 0
}

func (x *CDAssets) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *CDAssets) GetPurchaseTime() uint64 {
	if x != nil {
		return x.PurchaseTime
	}
	return 0
}

func (x *CDAssets) GetPrice() *PriceInfo {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *CDAssets) GetSigned() bool {
	if x != nil {
		return x.Signed
	}
	return false
}

var File_pb_assets_proto protoreflect.FileDescriptor

const file_pb_assets_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/assets.proto\x12\x02pb\"\x94\x01\n" +
	"\n" +
	"AssetsMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x04R\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12$\n" +
	"\x04book\x18\x04 \x01(\v2\x0e.pb.BookAssetsH\x00R\x04book\x12\x1e\n" +
	"\x02cd\x18\x05 \x01(\v2\f.pb.CDAssetsH\x00R\x02cdB\b\n" +
	"\x06detail\"k\n" +
	"\tPriceInfo\x12!\n" +
	"\x04unit\x18\x01 \x01(\x0e2\r.pb.PriceUnitR\x04unit\x12\x14\n" +
	"\x05price\x18\x02 \x01(\rR\x05price\x12%\n" +
	"\x0epurchase_price\x18\x03 \x01(\rR\rpurchasePrice\"\xe1\x01\n" +
	"\n" +
	"BookAssets\x12\x16\n" +
	"\x06author\x18\x01 \x03(\tR\x06author\x12\x1c\n" +
	"\tpublisher\x18\x02 \x01(\tR\tpublisher\x12\x10\n" +
	"\x03tag\x18\x03 \x03(\tR\x03tag\x12)\n" +
	"\blanguage\x18\x04 \x01(\x0e2\r.pb.LanguagesR\blanguage\x12#\n" +
	"\rpurchase_time\x18\x05 \x01(\x04R\fpurchaseTime\x12#\n" +
	"\x05price\x18\x06 \x01(\v2\r.pb.PriceInfoR\x05price\x12\x16\n" +
	"\x06signed\x18\a \x01(\bR\x06signed\"\x89\x02\n" +
	"\bCDAssets\x12\x16\n" +
	"\x06author\x18\x01 \x03(\tR\x06author\x12\x1c\n" +
	"\tpublisher\x18\x02 \x01(\tR\tpublisher\x12\x12\n" +
	"\x04Year\x18\x03 \x01(\rR\x04Year\x12)\n" +
	"\blanguage\x18\x04 \x01(\x0e2\r.pb.LanguagesR\blanguage\x12\x14\n" +
	"\x05track\x18\x05 \x01(\rR\x05track\x12\x10\n" +
	"\x03tag\x18\x06 \x03(\tR\x03tag\x12#\n" +
	"\rpurchase_time\x18\a \x01(\x04R\fpurchaseTime\x12#\n" +
	"\x05price\x18\b \x01(\v2\r.pb.PriceInfoR\x05price\x12\x16\n" +
	"\x06signed\x18\t \x01(\bR\x06signed*]\n" +
	"\tLanguages\x12\x13\n" +
	"\x0fUnknownLanguage\x10\x00\x12\x15\n" +
	"\x11SimplifiedChinese\x10\x01\x12\x16\n" +
	"\x12TraditionalChinese\x10\x02\x12\f\n" +
	"\bJapanese\x10\x03*<\n" +
	"\tPriceUnit\x12\x14\n" +
	"\x10UnknownPriceUnit\x10\x00\x12\a\n" +
	"\x03CNY\x10\x01\x12\a\n" +
	"\x03JPY\x10\x02\x12\a\n" +
	"\x03USD\x10\x03B\aZ\x05../pbb\x06proto3"

var (
	file_pb_assets_proto_rawDescOnce sync.Once
	file_pb_assets_proto_rawDescData []byte
)

func file_pb_assets_proto_rawDescGZIP() []byte {
	file_pb_assets_proto_rawDescOnce.Do(func() {
		file_pb_assets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_assets_proto_rawDesc), len(file_pb_assets_proto_rawDesc)))
	})
	return file_pb_assets_proto_rawDescData
}

var file_pb_assets_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_assets_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_assets_proto_goTypes = []any{
	(Languages)(0),     // 0: pb.Languages
	(PriceUnit)(0),     // 1: pb.PriceUnit
	(*AssetsMeta)(nil), // 2: pb.AssetsMeta
	(*PriceInfo)(nil),  // 3: pb.PriceInfo
	(*BookAssets)(nil), // 4: pb.BookAssets
	(*CDAssets)(nil),   // 5: pb.CDAssets
}
var file_pb_assets_proto_depIdxs = []int32{
	4, // 0: pb.AssetsMeta.book:type_name -> pb.BookAssets
	5, // 1: pb.AssetsMeta.cd:type_name -> pb.CDAssets
	1, // 2: pb.PriceInfo.unit:type_name -> pb.PriceUnit
	0, // 3: pb.BookAssets.language:type_name -> pb.Languages
	3, // 4: pb.BookAssets.price:type_name -> pb.PriceInfo
	0, // 5: pb.CDAssets.language:type_name -> pb.Languages
	3, // 6: pb.CDAssets.price:type_name -> pb.PriceInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pb_assets_proto_init() }
func file_pb_assets_proto_init() {
	if File_pb_assets_proto != nil {
		return
	}
	file_pb_assets_proto_msgTypes[0].OneofWrappers = []any{
		(*AssetsMeta_Book)(nil),
		(*AssetsMeta_Cd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_assets_proto_rawDesc), len(file_pb_assets_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_assets_proto_goTypes,
		DependencyIndexes: file_pb_assets_proto_depIdxs,
		EnumInfos:         file_pb_assets_proto_enumTypes,
		MessageInfos:      file_pb_assets_proto_msgTypes,
	}.Build()
	File_pb_assets_proto = out.File
	file_pb_assets_proto_goTypes = nil
	file_pb_assets_proto_depIdxs = nil
}
